In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Rakhi Bhardwaj\Desktop\mutual_fund_project\data\raw\icici_bluechip.csv")

In [3]:
df.head()

         date       nav
0  23-06-2026  107.5421
1  22-06-2026  108.4681
2  19-06-2026  107.9636
3  18-06-2026  108.0081
4  17-06-2026  107.5348

In [4]:
df.head()

         date       nav
0  23-06-2026  107.5421
1  22-06-2026  108.4681
2  19-06-2026  107.9636
3  18-06-2026  108.0081
4  17-06-2026  107.5348

In [5]:
df.shape

(3323, 2)

In [7]:
df.dtypes

date        str
nav     float64
dtype: object

In [9]:
df.isnull().sum()

date    0
nav     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['date', 'nav'], dtype='str')

In [12]:
df.describe

<bound method NDFrame.describe of             date       nav
0     23-06-2026  107.5421
1     22-06-2026  108.4681
2     19-06-2026  107.9636
3     18-06-2026  108.0081
4     17-06-2026  107.5348
...          ...       ...
3318  08-01-2013   15.1146
3319  07-01-2013   15.0913
3320  04-01-2013   15.0702
3321  03-01-2013   15.0737
3322  02-01-2013   15.0253

[3323 rows x 2 columns]>

In [13]:
df.tail()

            date      nav
3318  08-01-2013  15.1146
3319  07-01-2013  15.0913
3320  04-01-2013  15.0702
3321  03-01-2013  15.0737
3322  02-01-2013  15.0253

In [14]:
df.tail(10)

            date      nav
3313  15-01-2013  14.9813
3314  14-01-2013  14.9767
3315  11-01-2013  14.8886
3316  10-01-2013  15.0619
3317  09-01-2013  15.0517
3318  08-01-2013  15.1146
3319  07-01-2013  15.0913
3320  04-01-2013  15.0702
3321  03-01-2013  15.0737
3322  02-01-2013  15.0253

In [15]:
df.head()

         date       nav
0  23-06-2026  107.5421
1  22-06-2026  108.4681
2  19-06-2026  107.9636
3  18-06-2026  108.0081
4  17-06-2026  107.5348

In [16]:
df.head(10)

         date       nav
0  23-06-2026  107.5421
1  22-06-2026  108.4681
2  19-06-2026  107.9636
3  18-06-2026  108.0081
4  17-06-2026  107.5348
5  16-06-2026  107.0140
6  15-06-2026  106.5977
7  12-06-2026  105.2124
8  11-06-2026  102.8808
9  10-06-2026  103.1873

In [17]:
len(df)

3323

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3323 entries, 0 to 3322
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3323 non-null   str
 1   nav     3323 non-null   float64
dtypes: float64(1), str(1)
memory usage: 52.1 KB