In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Rakhi Bhardwaj\Desktop\mutual_fund_project\data\raw\axis_bluechip.csv")

In [3]:
df.head()

         date        nav
0  23-06-2026  6200.8511
1  22-06-2026  6199.4871
2  19-06-2026  6195.7815
3  18-06-2026  6194.6520
4  17-06-2026  6193.3504

In [4]:
df.shape

(3581, 2)

In [5]:
df.dtypes

date        str
nav     float64
dtype: object

In [6]:
df.isnull().sum()

date    0
nav     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['date', 'nav'], dtype='str')

In [11]:
df.describe()

               nav
count  3581.000000
mean   3403.442118
std    1983.448769
min      23.992000
25%    3091.870700
50%    3857.265300
75%    4759.954400
max    6200.851100

In [12]:
df.tail()

            date      nav
3576  04-01-2013  24.0147
3577  03-01-2013  24.0092
3578  02-01-2013  24.0036
3579  01-01-2013  23.9979
3580  31-12-2012  23.9920

In [13]:
df.tail(10)

            date      nav
3571  10-01-2013  24.0479
3572  09-01-2013  24.0424
3573  08-01-2013  24.0369
3574  07-01-2013  24.0314
3575  06-01-2013  24.0258
3576  04-01-2013  24.0147
3577  03-01-2013  24.0092
3578  02-01-2013  24.0036
3579  01-01-2013  23.9979
3580  31-12-2012  23.9920

In [14]:
len(df)

3581

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3581 entries, 0 to 3580
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3581 non-null   str
 1   nav     3581 non-null   float64
dtypes: float64(1), str(1)
memory usage: 56.1 KB